### ISSUE TITLE
有一个很折磨人的bug咨询

### ISSUE THREAD

**Issue by havefunbb** [yeyupiaoling/LearnPaddle#2]
`在执行你的note9，note10的时候报下面的错：
Check failed: mapGet(type, creatorMap_, &creator) Unknown class type: cudnn_conv

请问有什么解决方案吗？

**Comment by havefunbb** [comment]
会不会是因为我的电脑不支持width_avx？

**Comment by yeyupiaoling** [comment]
@havefunbb 这个报的应该是GPU的错误。你是GPU环境是否正常？

**Comment by yeyupiaoling** [comment]
@havefunbb avx指令集是CPU的，应该跟它没什么关系。

**Comment by wuwusky** [comment]
@havefunbb 这是在那个例子中的VGG_SSD_net中网络构建是用了cudnn的一些层定义，你如果gpu环境配置不合适肯定回报错，看样子应该是你配置了cpu的paddle确调用cudnn_conv来构建网络，肯定找不定该类型啦

**Comment by yeyupiaoling** [comment]
@havefunbb 您的问题解决了吗？
