### ISSUE TITLE
运行note9的预测程序infer没有出结果

### ISSUE THREAD

**Issue by liuliyalei** [yeyupiaoling/LearnPaddle#4]
运行infer程序没有报错，但是就是没有结果，没有在infer.res和infer.txt写入预测结果，请问这是什么原因

**Comment by yeyupiaoling** [comment]
@liuliyalei 整个过程都没有报错吗？如果这个的话，应该是没有预测到结果是大于0.3的，所以会被筛选掉。建议增加训练的pass，然模型收敛。

**Comment by liuliyalei** [comment]
那应该怎么解决？我觉得我的权限都是不受限的呀，这是啥权限受限了？ @yeyupiaoling

**Comment by yeyupiaoling** [comment]
@liuliyalei 你是用命令运行吗？你的是在root用户下操作吗？

**Comment by liuliyalei** [comment]
我在文件夹下打开终端，然后运行jupyter notebook，然后运行TestServer.ipynb文件

`liul9@ubuntu:~/paddle-models/web$ jupyter notebook`

![qq 20180709154010](https://user-images.githubusercontent.com/40382579/42437037-64e2ff3a-838e-11e8-8fb6-30b3cce56a24.png)
![qq 20180709153928](https://user-images.githubusercontent.com/40382579/42437039-65281728-838e-11e8-98d8-9cf3f6844c4d.png)

**Comment by yeyupiaoling** [comment]
你全部操作都在root用户上操作试试
