### ISSUE TITLE
执行train.py提示'module' object has no attribute 'batch'

### ISSUE THREAD

**Issue by rigelzhang** [yeyupiaoling/LearnPaddle#5]
![_20180718155818](https://user-images.githubusercontent.com/12620032/42867906-74f14870-8aa3-11e8-8f0e-a540b5f677e2.png)
执行train.py提示paddle.batch属性不存在，好奇怪，已经导入paddle.v2了

**Comment by rigelzhang** [comment]
0.11

**Comment by rigelzhang** [comment]
想问下楼主，用的那个版本

**Comment by yeyupiaoling** [comment]
@rigelzhang 我之前有的也是0.11.0，现在用0.14.0都没有问题呢。你更新一下paddlepaddle。

**Comment by yeyupiaoling** [comment]
@rigelzhang 您好，问题解决了吗？
