### ISSUE TITLE
VGG16量化模型的测试和每一层输入输出特征值提取问题

### ISSUE THREAD

**Issue by taoja12** [yeyupiaoling/LearnPaddle#7]
我是将tensorflow vgg16模型通过X2Paddle转换成paddle模型，产生了inference_model和model_with_code两个文件夹，之后使用无校准数据量化对inference_model里的参数进行量化，成功后生成的模型参数体积减小了，想问量化的原理可以从哪里看到？量化后的模型每一层特征值如何提取出来？

**Comment by yeyupiaoling** [comment]
@taoja12 你应该是来错地方了，如果你是用的是Paddle Lite，可以在https://github.com/PaddlePaddle/Paddle-Lite 提问。
你问的获取每一层输入可以查看这个文档，如果你是用的是Paddle Lite: https://paddle-https://paddle-lite.readthedocs.io/zh/latest/api_reference/cxx_api_doc.html#getinputbyname-name
